// require 



// class mise constructor // called by board -
  // class const 
// this size - default for testing to be refactored later
// this pos = default - generates hand position -
// this angle = [x y zed] relative to board 
// this isFixed = default true
// this momentum? // possibly useful later to assign sustained movement direction
// calls handThatHolds function on instantiation
// cutFace = default fresh
    

//class methods

// handThatHolds (position, size)

// dropped
  //cause roll away 
  // instability on cutting ** refactor to be present if time

// chop(kPos)
  // kPos will be a line generated by extending knife coords to face plane of mise
  // ON CHOP : cutFace resigned relative to angle / pos of kPos